#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Test for a process with ARM architecture.
HELPTEXT
    echo
    printf 'Usage: %q %s\n' "$(basename "$1")" '[32|64] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

case "$(uname --machine)" in
    # armv5tel, armv6l, armv7l
    armv*)  exec [ -z "$1" -o "$1" = 32 ];;
    aarch64)
	    exec [ -z "$1" -o "$1" = 64 ];;
    *)	    exit 1;;
esac
