#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Test whether the kernel is running in 32 or 64-bit mode.
HELPTEXT
    echo
    printf 'Usage: %q %s\n' "$(basename "$1")" '32|64 [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
if [ $# -ne 1 ]; then
    printUsage "$0" >&2
    exit 2
fi

bitness="$(getconf LONG_BIT)"
[ "$1" = "$bitness" ]
