#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Test for Redhat variant and/or release; succeeds if at least one passed requirement is true.
HELPTEXT
    echo
    printf 'Usage: %q %s\n' "$(basename "$1")" '[--variant centos|fedora|rhel|amzn|...] [-N[.n]|[!]N[.n]|N[.n]+|N[.n]-M[.m]|N[.n]%M[.m] [...]] [-?|-h|--help]'
}
variantRequirement=
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
    --variant)		shift; variantRequirement="$1"; shift;;
esac

source /etc/os-release || exit 3
[ -n "$ID" -a -n "$VERSION_ID" ] || exit 3

contains rhel "$ID" $ID_LIKE || exit 3
[ -z "$variantRequirement" ] || [ "$ID" = "$variantRequirement" ] || exit 1

[ $# -eq 0 ] && exit 0

VERSIONREQUIREMENT_BASE_VERSION="$VERSION_ID" exec versionRequirement "$@"
