#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Test for Ubuntu release; succeeds if at least one passed requirement is true.
HELPTEXT
    echo
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-YY.MM|[!]YY.MM|YY.MM+|YY.MM-YY.MM|YY.MM%YY.MM [...]] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

[ "$(lsb_release -is 2>/dev/null)" = Ubuntu ] || exit 3

ubuntuVersion="$(lsb_release -rs 2>/dev/null)" || exit 3
ubuntuVersion="${ubuntuVersion//./}"

[ $# -eq 0 ] && exit 0

VERSIONREQUIREMENT_BASE_VERSION="$ubuntuVersion" exec versionRequirement "${@//./}"
