#!/bin/bash
shopt -qs extglob

printUsage()
{
    cat <<HELPTEXT
Test for Ubuntu release; succeeds if at least one passed requirement is true.
HELPTEXT
    echo
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-YY.MM|YY.MM|YY.MM+|YY.MM-YY.MM|YY.MM%YY.MM [...]] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

[ "$(lsb_release -is 2>/dev/null)" = Ubuntu ] || exit 3

ubuntuVersion="$(lsb_release -rs 2>/dev/null)" || exit 3
ubuntuVersion="${ubuntuVersion//./}"

[ $# -eq 0 ] && exit 0

for versionRequirement
do
    versionRequirement="${versionRequirement//./}"
    case "$versionRequirement" in
	-+([0-9]))	    [ $ubuntuVersion -le ${versionRequirement#-} ] && exit 0;;
	+([0-9])+)	    [ $ubuntuVersion -ge ${versionRequirement%+} ] && exit 0;;
	+([0-9])-+([0-9]))  minVersion=${versionRequirement%-*}
			    maxVersion=${versionRequirement#*-}
			    [ $ubuntuVersion -ge $minVersion -a $ubuntuVersion -le $maxVersion ] && exit 0
			    ;;
	+([0-9])%+([0-9]))  minVersion=${versionRequirement%\%*}
			    maxVersion=${versionRequirement#*%}
			    [ $ubuntuVersion -lt $minVersion -o $ubuntuVersion -gt $maxVersion ] && exit 0
			    ;;
	+([0-9]))	    [ $ubuntuVersion -eq $versionRequirement ] && exit 0;;
	*)		    printf >&2 'ERROR: Invalid version requirement: %s\n' "$versionRequirement"
			    exit 2
			    ;;
    esac
done
exit 1
